### ISSUE TITLE
建议在新窗口打开搜索界面

### ISSUE THREAD

**Issue by mingjinglyh** [5iux/sou#15]
把网址设置成浏览器主页，搜索的时候会从本页打开，需要网址导航的时候需要重新打开，不太方便，建议可以从新窗口打开搜索结果。

**Comment by wuxiedi** [comment]
我看代码里已经是写的_blank但是还是从当前窗口打开，很难搞

**Comment by wuxiedi** [comment]
对啊，对PHP不太了解，修改也不太会，改了target属性但是还是在原窗口打开，希望作者修改或发布更改代码

**Comment by 5iux** [comment]
加上了

**Comment by Niksend** [comment]
臣附议，希望可以改变下创建新窗口的方式，

![](https://i.loli.net/2019/12/21/gKAvId6WJ4lwHzq.png)

另外问下 dalao ，像这个

![](https://raw.githubusercontent.com/5iux/sou/master/img0726.gif)

[README](https://github.com/5iux/sou/blob/master/README.md#gif) 里的天气api是哪家的，这个版本的天气会这样显示 

![](https://i.loli.net/2019/12/21/qZeSvmz8AhDgHaT.png)

谢谢
