### ISSUE TITLE
不想要搜索，只要右侧的那个导航页，应该怎么处理

### ISSUE THREAD

**Issue by lePig** [5iux/sou#24]
想弄一个自己的导航，包括经常浏览的网站。看着右侧弹出的那个深蓝色页面挺好看的。 
因为首页太白了很刺眼。

**Comment by lePig** [comment]
时隔数月发现作者增加了暗黑模式。我部署了以后发现PC端chrome默认是白色的，但是我用手机(iphone已设置了暗黑模式)访问是默认暗黑模式。
如何让PC浏览器 浏览默认也是暗黑模式呢？

**Comment by 5iux** [comment]
PC一般是需要win10设置了“设置-个性化-颜色-默认应用模式-黑暗”

**Comment by CiaoBye** [comment]
为什么网页右侧一直是黑色 无论是更改dark 还是 light
