### ISSUE TITLE
能否增加点图标，尤其是音乐类各知名站点的图标！

### ISSUE THREAD

**Issue by x2013** [5iux/sou#28]
1.亲，能否增加点音乐类的站点图标，那个不会增加图标，不然就不来麻烦作者君了！
PS：就增加6个站点的图标就成，分别为：网易云音乐，虾米音乐，QQ音乐，咪咕音乐，酷狗音乐，酷我音乐！
2.亲，能否增加一个钱币的图标！
PS：美元或RMB 那个图标都成！

**Comment by 5iux** [comment]
图标的话建议去阿里图标库自己选一套，在那里你会发现新世界[https://www.iconfont.cn/](https://www.iconfont.cn/)

**Comment by x2013** [comment]
关键是不会增加，给个教程，怎么增加图标！！！
