### ISSUE TITLE
新的天气api更新太慢了

### ISSUE THREAD

**Issue by WoChen5770** [5iux/sou#8]
广州还是5.30的数据，而旧版已经10点的了

**Comment by 5iux** [comment]
免费插件，总有这样那样的问题的，这里的页面是个示例。同类型的api挺多，可以根据需求自己更换下。

**Comment by WoChen5770** [comment]
推荐个api 彩云天气
这个api的免费版好像是1000次/天，个人用应该够了。
实况天气每30秒更新一次

**Comment by 5iux** [comment]
正在尝试和风，3000次每天，带图标的，回头发布
